modLoader="javafml"
loaderVersion="[41,)"
license="All rights reserved"
issueTrackerURL="https://github.com/Craftjakob/More-Bows-CJ/issues"

[[mods]]
modId="morebows"
version="${file.jarVersion}"
displayName="More Bows"
logoFile="icon.png"
credits="Thank you for installing this mod!"
authors="Craftjakob"
#updateJSONURL="https://I'm_not_working.com"
displayURL="https://github.com/Craftjakob/More-Bows-CJ/wiki"
description='''
This mod adds new bow version. 
All versions of Bows: 
Iron Bow, Copper Bow, Gold Bow, Diamond Bow, Emerald Bow, Netherite Bow
'''
[[dependencies.morebows]]
    modId="forge"
    mandatory=true
    versionRange="[41,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.morebows]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19,1.20)"
    ordering="NONE"
    side="BOTH"
